courses/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('courses', views.courses, name = "courses"),
	path('courses/<int:course_id>/', views.course_detail, name='course_detail'),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name = "home"),
]

website/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('user.urls')),
    path('', include('courses.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q

class Course(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(blank=True)
    description = models.TextField()
    specific_content = models.TextField(blank=True)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.teacher is None:
            self.teacher = User.objects.filter(Q(is_superuser=True) | Q(is_staff=True)).first()
        super().save(*args, **kwargs)

    def __str__(self):  # New method
        return self.title

class Image(models.Model):
    course = models.ForeignKey(Course, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField()

    def __str__(self):
        return f"{self.course.title} Image({self.id})"


class Video(models.Model):
    course = models.ForeignKey(Course, related_name='videos', on_delete=models.CASCADE)
    url = models.URLField()  # Use URLField to store YouTube video URLs

    def __str__(self):
        return f"{self.course.title} Video({self.id})"


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    # any other lesson-specific data you have

    def __str__(self):
        return f"{self.course} - {self.title}"

class Quiz(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    question = models.TextField()

    def __str__(self):
        return f"{self.lesson.title} Quiz({self.id})" 

class QuizOption(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    answer = models.TextField()
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quiz.question} Option({self.id})"

courses/views.py
from django.shortcuts import render, get_object_or_404
from .models import Course


# Create your views here.

def courses(request):
	courses = Course.objects.all()
	return render(request, 'courses.html', {'courses':courses})\


def course_detail(request, course_id):
	course = get_object_or_404(Course, id=course_id)
	return render(request, 'course_detail.html', {'course': course})

courses/templates/course_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="course-info">
        <h1 class="course-title text-center">{{ course.title }}</h1>
</div>
<div class="container">
    <div class="slick-slider mt-5">
    {% for image in course.images.all %}
        <div>
            <a href="{{ image.image.url }}" data-lightbox="course-image">
                <img src="{{ image.image.url }}" style="width: 100%;">
            </a>
        </div>
    {% endfor %}
</div>

</div>

<div class="course-info">
        <p class="course-description mt-3">{{ course.description }}</p>
        <p class="course-description-question"> What is {{ course.title }} ?</p>
        <p class="course-description-answer">{{course.specific_content}}</p>
</div>

<hr>

<h2 class = "text text-center">Watch the following video and then proceed further.</h2>

<div class="container text-center">

    <!-- YouTube video -->
	<div class="embed-responsive embed-responsive-16by9 mt-5" style="width: 100%; height: auto;">
	    <iframe class="embed-responsive-item" src="{{ course.videos.first.url }}" style="width: 80%; height: 600px;" allowfullscreen></iframe>
	</div>

</div>


<div class="container-lesson">
    {% for lesson in course.lesson_set.all %}
        {% if forloop.counter0|divisibleby:2 %}
            <div class="row">
        {% endif %}
            <div class="lesson">
                <h2 class="lesson-title">{{ lesson.title }}</h2>
                <p class="lesson-content">{{ lesson.content }}</p>
            </div>
        {% if forloop.counter|divisibleby:2 or forloop.last %}
            </div>
        {% endif %}
    {% endfor %}
</div>



<style>

.container-lesson {
    text-align: center;
    margin-top: 50px;
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    grid-gap: 20px;
}

.row {
    display: contents; 
}

.lesson-title {
    color:#FF6969;
    font-size: 2.5rem;
    font-weight: bold;
    padding: 30px 10%;  // adjust as needed
    margin-top: 30px;
}

.lesson-content {
    color:black;
    font-size: 1.2rem;
    padding: 0 15%;  // adjust as needed
}


	.text{
		color: #116D6E;
		padding-top:10px;
	}

	.embed-responsive.embed-responsive-16by9 {
	    width: 100%;
	    height: 100%;
	}


    .course-info {
        text-align: center;
        margin-bottom: 20px;
        margin-top: 20px;
    }

    .course-title {
        margin-top: 20px;
        font-size: 3.2rem;
        font-weight: bold;
        color: #116D6E;
        text-decoration: underline;
    }

    .course-description {
        font-size: 16px;
        color: black;
        padding: 30px 20%;
	}
	.course-description-question{
		font-size: 2.5rem;
        color: crimson;
        padding: 0 20%;
        padding-bottom: 20px;
	}
	.course-description-answer{
		font-size: 16px;
        color: black;
        padding: 0 20%;
        padding-bottom: 20px;
	}


	/*	slick style	*/
 	.slick-slider {
        position: relative;
        padding: 0 40px;
    }

    .slick-slider .slick-slide {
        margin: 0 20px;
     }

    /* button style */
    .slick-slider .slick-prev,
    .slick-slider .slick-next {
        font-size: 0;
        line-height: 0;
        position: absolute;
        top: 50%;
        display: block;
        width: 40px;
        height: 40px;
        padding: 0;
        transform: translate(0, -50%);
        cursor: pointer;
        color: transparent;
        border: none;
        outline: none;
        background: #888888;
        border-radius: 50%;
        z-index: 2;
    }
    .slick-slider .slick-prev {
        left: -20px;
    }
    .slick-slider .slick-next {
        right: -20px;
    }
    .slick-slider .slick-prev:before,
    .slick-slider .slick-next:before {
        font-family: 'Font Awesome 5 Free';
        font-size: 20px;
        font-weight: 900;
        line-height: 1;
        color: white;
        opacity: .75;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
    .slick-slider .slick-prev:before {
        content: '\f104';
    }
    .slick-slider .slick-next:before {
        content: '\f105';
    }
</style>


<!-- js for slick slider(image slide_show) -->
<script>
        $(document).ready(function(){
            $('.slick-slider').slick({
                slidesToShow: 3,
                slidesToScroll: 1,
                autoplay: true,
                autoplaySpeed: 2000,
                responsive: [
                    {
                        breakpoint: 1024,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 600,
                        settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1
                        }
                    }
                ]
            });
        });
</script>   
{% endblock %}

courses/templates/courses.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<h2>Choose any of the following subjects and start learning!</h2>

<br><br><hr>


<div class = "course-container">

	{% for course in courses %}

	<div class = "course">
		<div class="course_image">
			{% if course.image %}
			<img src="{{ course.image.url }}">
			{% else %}
			<img class = "not_available_image" src="{% static 'courses/images/na.png' %}" alt="Course Image">
			{% endif %}
		</div>
		<div class = "content">
			<div class="title">{{ course.title }}</div>
			<div class="course_teacher"><span> Teacher:   </span>
				{% if course.teacher %}
	        	<p class="member_subject"> {{ course.teacher.get_full_name }}</p>
	        	{% else %}
	        	<p class="member_subject"> N/A</p>
	        	{% endif %}
	        </div>
			<a href="{% url 'course_detail' course.id %}">
                <button class = "go_to_course_btn">Go to course</button>
            </a>
		</div>
	</div>

	{% endfor %}

</div>

	

<style>

h2{
	text-align: center;
	padding-top: 40px;
	color: #116D6E;
}


.course-container{
    padding: 60px 0px;
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-gap: 80px; /* adjust for desired spacing */
/*    justify-items: center; */
    margin: 0 auto;
    max-width: 1400px; /* adjust as necessary */
}

.course{
    display: flex;
    flex-direction: column;
    max-width: 380px;
    align-items: start;
    box-shadow: 0 6px 4px 0 rgba(0,0,0,0.3), 0 2px 12px 0 rgba(0,0,0,0.19);
    background-color: white;
    border-radius: 20px;
}
.course_image{
    width: 100%;
    height: 230px;
}
.course_image img{
	object-fit: cover;
    border-radius: 20px;
    overflow: hidden;
    width: 100%;
    height: 100%;
}

.content{
    padding: 10px 20px;
    display: flex;
    flex-direction: column;
    align-items: start; /* Aligns items to the start/left of the flex container */
}

.title{
    display: flex; /* Makes elements in title on same line */
    color: #FF6969;
    text-transform: uppercase;
    font-size: 1.3rem;
    margin: 5px 0px;
    font-weight: bold;
}

.course_teacher{
    display: flex; /* Makes elements in course_teacher on same line */
    color: blue;
    margin-top: 5px;
    margin-bottom: 10px;
}
.course_teacher span{
	font-size: 1rem;
	color: black;
}
.course_teacher p{
	font-size: 1rem;
	color: black;
	font-weight: bold;
	text-transform: uppercase;
}
.go_to_course_btn{
  background-color: #654E92;
  margin: 5px auto 0px ;
  border-radius: 12px;
  border: 2px solid #366473;
  padding: 14px 50px;
  outline: none;
  color: white;
  cursor: pointer;
  transition: 0.25px;
  align-self: center;
}
.go_to_course_btn:hover{
	background-color: #6C9BCF;
}

@media (max-width: 768px) {
    .course-container {
        grid-template-columns: 1fr;
    }
    .course {
        margin: 20px auto;
    }
}
</style>

{% endblock %}